# joystick settings
btn_square: 0
btn_cross: 1
btn_circle: 2
btn_triangle: 3

# vicon names
jackal_name: "alvin_jk"
crazyflie_name: "alvin_cf"

# transforms
jk_t_cf: [  0.00719441, -0.01398, 0.0207427 ]
jk_R_cf: [ 0.00324669, 0.01396596, -0.00439251, 0.99988755 ]

# visualizer
serial_port: "/dev/ttyACM1"
bound_accuracy: 0.15
