# joystick settings
btn_square: 0
btn_cross: 1
btn_circle: 2
btn_triangle: 3

# vicon names
jackal_name: "alvin_jk"
crazyflie_name: "alvin_cf"

# transforms
jk_t_cf: [0.0295106, -0.00416421, 0.02068458]
